site_name: yt-dlp
site_url: https://wahlstrommm.github.io/yt-dlp/
plugins:
  - search
  - encryptcontent:
      global_password: "" # Ingen globalt lösenord, eftersom vi använder specifika lösenord
      redirect_url: /404.html
extra_css:
  - styles.css
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.tracking
    - navigation.instant
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime
extra:
  social:
    - icon: material/github
      link: https://github.com/wahlstrommm
    - icon: material/twitter
      link: https://twitter.com
    - icon: material/linkedin
      link: https://www.linkedin.com/in/magnus-vahlstrom
  markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - admonition
    - pymdownx.arithmatex:
        generic: true
    - footnotes
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.mark
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/wahlstrommm"  target="_blank" rel="noopener">Magnus Vahlström</a>
